// REDUX ACTION TYPES

// Set API Config
export const SETAPICONFIG = "SETAPICONFIG";

export const SWITCHLANGUAGE = "SWITCHLANGUAGE";
export const SWITCHDATE = "SWITCHDATE";

// Set Search Term
export const SETSEARCHTERM = "SETSEARCHTERM";

// National Overview Map
export const SLIDERADIUS = "SLIDERADIUS";

// Carousel & Map
export const SETCAROUSELCOORDINATES = "SETCAROUSELCOORDINATES";

// Flood Carousel & Map
export const SETFLOODCOORDINATES = "SETFLOODCOORDINATES";

// Set Primary Location
export const SETPRIMARYLOCATION = "SETPRIMARYLOCATION"

// Set Additional Location
export const SETADDITIONALLOCATION = "SETADDITIONALLOCATION"

// Remove Additional Location
export const REMOVEADDITIONALLOCATION = "REMOVEADDITIONALLOCATION"

// Set Data Type
export const SETDATATYPE = "SETDATATYPE"

// Set Location Preference
export const SETLOCATIONPREFERENCE = "SETLOCATIONPREFERENCE"

// Set Pluviometer Data
export const SETPLUVIOMETERDATA = "SETPLUVIOMETERDATA"

// Set Pluviometer Data
export const REMOVEPLUVIOMETERDATA = "REMOVEPLUVIOMETERDATA"

// Set FLOODZONE Data
export const SETFLOODDATA = "SETFLOODDATA"

// Set FLOODZONE Data
export const REMOVEFLOODDATA = "REMOVEFLOODDATA"

// Cluster Rainfall Map
export const CLUSTERRAINFALLMAP = "CLUSTERRAINFALLMAP"

// SET OVERVIEW MAP VIEW
export const SETOVERVIEWMAPVIEW = "SETOVERVIEWMAPVIEW"

// SET CITIZEN RAINFALL EVENTS
export const SETCITIZENRAINFALLEVENTS = "SETCITIZENRAINFALLEVENTS"

// REMOVE CITIZEN RAINFALL EVENTS
export const REMOVECITIZENRAINFALLEVENTS = "REMOVECITIZENRAINFALLEVENTS"

// SET CITIZEN FLOODZONES EVENTS
export const SETCITIZENFLOODZONESEVENTS = "SETCITIZENFLOODZONESEVENTS"

// REMOVE CITIZEN FLOODZONES EVENTS
export const REMOVECITIZENFLOODZONESEVENTS = "REMOVECITIZENFLOODZONESEVENTS"

// SET CITIZEN FLOODZONES EVENTS
export const SETCITIZENRIVERFLOODEVENTS = "SETCITIZENRIVERFLOODEVENTS"

// REMOVE CITIZEN FLOODZONES EVENTS
export const REMOVECITIZENRIVERFLOODEVENTS = "REMOVECITIZENRIVERFLOODEVENTS"