// REDUX ACTION TYPES

export const SWITCHLANGUAGE = "SWITCHLANGUAGE";
export const SWITCHDATE = "SWITCHDATE";

// National Overview Map
export const SLIDERADIUS = "SLIDERADIUS";

// Carousel & Map
export const SETCAROUSELCOORDINATES = "SETCAROUSELCOORDINATES";

// Set Primary Location
export const SETPRIMARYLOCATION = "SETPRIMARYLOCATION"